payment/routes/plan.py
from flask import Blueprint, request, render_template, redirect, url_for
from payment.integrations.signatures.signature_plan import SignaturePlanProxy
from payment.models.auto_recurring_model import AutoRecurringModel

plan_bp = Blueprint('plan', __name__, template_folder='templates')
SIGNATURE_PLAN = SignaturePlanProxy()


@plan_bp.route('/plan/register/', methods=['GET', 'POST'])
def register_plan():
    if request.method == "POST":
        data = request.form

        auto_reccurring = AutoRecurringModel(
            frequency=data.get("frequency"),
            frequency_type=data.get("frequency_type"),
            repetitions=data.get("repetitions"),
            billing_day=data.get("billing_day"),
            billing_day_proportional=data.get("billing_day_proportional"),
            free_trial_frequency=data.get("free_trial_frequency"),
            transaction_amount=data.get("transaction_amount"),
            currency_id=data.get("currency_id")
        )

        response = SIGNATURE_PLAN.add_signature_plan(
            reason=data.get("reason"),
            auto_recurring=auto_reccurring,
            back_url=data.get("back_url")
        )

        if response is None:
            return render_template("plan/response.html", response="error", message="Erro durante cadastramento do plano.")

        return redirect(url_for("plan.get_plan", plan_id=response['id']), 302)
    else:
        return render_template("plan/plan_register.html")


@plan_bp.route('/plan/<plan_id>/update/', methods=['GET', 'POST'])
def update_plan(plan_id):
    plan = SIGNATURE_PLAN.get_signature_plan(plan_id)

    if plan is None:
        return render_template("plan/response.html", response="error", message="Erro durante busca do plano.")

    if request.method == "POST":
        data = request.form

        auto_reccurring = AutoRecurringModel(
            frequency=data.get("frequency"),
            frequency_type=data.get("frequency_type"),
            repetitions=data.get("repetitions"),
            billing_day=data.get("billing_day"),
            billing_day_proportional=data.get("billing_day_proportional"),
            free_trial_frequency=data.get("free_trial_frequency"),
            transaction_amount=data.get("transaction_amount"),
            currency_id=data.get("currency_id")
        )

        response = SIGNATURE_PLAN.update_signature_plan(
            id=plan_id,
            reason=data.get("reason"),
            auto_recurring=auto_reccurring,
            back_url=data.get("back_url")
        )

        if response is None:
            return render_template("plan/response.html", response="error",
                                   message="Erro durante atualização do plano.")

        return redirect(url_for("plan.get_plan", plan_id=response['id']), 302)
    else:
        return render_template("plan/plan_register.html", plan=plan)


@plan_bp.route('/plan/', methods=['GET', ])
def get_plans():
    plans = SIGNATURE_PLAN.get_signature_plans()

    if plans is None:
        return render_template("plan/response.html", response="error", message="Erro durante busca dos planos.")

    return render_template("plan/plans.html", subscriptions=plans)


@plan_bp.route('/plan/<plan_id>/', methods=['GET', ])
def get_plan(plan_id):
    plan = SIGNATURE_PLAN.get_signature_plan(plan_id)
    print(plan)
    if plan is None:
        return render_template("plan/response.html", response="error", message="Erro durante busca do plano.")

    return render_template("plan/plan.html", subscription=plan)

payment/templates/plan/plan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subscriptions</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div>
        <h1 class="page-title">Planos de Assinatura</h1>
        <div class="card">
            <h3>{{ subscription.reason }}</h3>
            <p><strong>Status:</strong> {{ subscription.status }}</p>
            <p><strong>Valor:</strong> R$ {{ subscription.auto_recurring.transaction_amount }} / {{ subscription.auto_recurring.frequency_type }}</p>
            <p><strong>Repetições:</strong> {{ subscription.auto_recurring.repetitions }}</p>
            <p><strong>Criado em:</strong> {{ subscription.date_created }}</p>
            <p><strong>Última Modificação:</strong> {{ subscription.last_modified }}</p>
            <p><strong>Billing Day:</strong> Dia {{ subscription.auto_recurring.billing_day }}</p>
            <p><strong>Teste Grátis:</strong> {{ subscription.auto_recurring.free_trial.frequency }} {{ subscription.auto_recurring.free_trial.frequency_type }}</p>
            <p><strong>Moeda:</strong> {{ subscription.auto_recurring.currency_id }}</p>
            <p><strong>Coletor ID:</strong> {{ subscription.collector_id }}</p>
            <p><strong>Subscritos:</strong> {{ subscription.subscribed }}</p>
            <p><strong>Application ID:</strong> {{ subscription.application_id }}</p>

            <div style="margin-top: 15px;">
                <a href="{{ subscription.init_point }}" target="_blank"><button>Ver Checkout</button></a>
            </div>
        </div>
    </div>
</body>
</html>

payment/templates/plan/plan_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ 'Update Plan' if plan else 'Register Plan' }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <form method="POST" action="{{ url_for('plan.update_plan', plan_id=plan.id) if plan else url_for('plan.register_plan') }}" class="form">
        <h2>{{ 'Update Plan' if plan else 'Register New Plan' }}</h2>

        {% if plan %}
        <input type="hidden" name="id" value="{{ plan.id }}">
        {% endif %}

        <label>Razão:
            <input type="text" name="reason" value="{{ plan.reason if plan else '' }}" required>
        </label>

        <label>URL de retorno:
            <input type="text" name="back_url" value="{{ plan.back_url if plan else '' }}" required>
        </label>

        <fieldset>
            <legend>Recorrência</legend>

            <label>Frequência:
                <input type="number" name="frequency" value="{{ plan.auto_recurring.frequency if plan else '' }}" required>
            </label>

            <label>Tipo da frequência:
                <select name="frequency_type" required>
                    <option value="days" {% if plan and plan.auto_recurring.frequency_type == 'days' %}selected{% endif %}>Dias</option>
                    <option value="months" {% if plan and plan.auto_recurring.frequency_type == 'months' %}selected{% endif %}>Meses</option>
                </select>
            </label>

            <label>Repetições:
                <input type="number" name="repetitions" value="{{ plan.auto_recurring.repetitions if plan else '' }}" required>
            </label>

            <label>Dia da cobrança:
                <input type="number" name="billing_day" min="1" max="28" value="{{ plan.auto_recurring.billing_day if plan else '' }}">
            </label>

            <label>Cobrança proporcional:
                <select name="billing_day_proportional" required>
                    <option value="true" {% if plan and plan.auto_recurring.free_trial == 'true' %}selected{% endif %}>Sim</option>
                    <option value="false" {% if plan and plan.auto_recurring.free_trial == 'false' %}selected{% endif %}>Não</option>
                </select>
            </label>

            <label>Período de testes:
                <input type="number" name="free_trial_frequency" value="{{ plan.auto_recurring.free_trial.frequency if plan else '' }}">
            </label>

            <label>Valor da transação:
                <input type="number" step="0.01" name="transaction_amount" value="{{ plan.auto_recurring.transaction_amount if plan else '' }}" required>
            </label>

            <label>Moeda:
                <select name="currency_id" required>
                    <option value="BRL" {% if plan and plan.auto_recurring.currency_id == 'BRL' %}selected{% endif %}>Real Brasileiro</option>
                    <option value="USD" {% if plan and plan.auto_recurring.currency_id == 'USD' %}selected{% endif %}>Dollar</option>
                    <option value="ARS" {% if plan and plan.auto_recurring.currency_id == 'ARS' %}selected{% endif %}>Peso Argentino</option>
                    <option value="PEN" {% if plan and plan.auto_recurring.currency_id == 'PEN' %}selected{% endif %}>Sol Peruano</option>
                    <option value="COP" {% if plan and plan.auto_recurring.currency_id == 'COP' %}selected{% endif %}>Peso Colombiano</option>
                    <option value="UYU" {% if plan and plan.auto_recurring.currency_id == 'UYU' %}selected{% endif %}>Peso Uruguayo</option>
                    <option value="VES" {% if plan and plan.auto_recurring.currency_id == 'VES' %}selected{% endif %}>Bolivar Venezolano</option>
                    <option value="CLP" {% if plan and plan.auto_recurring.currency_id == 'CLP' %}selected{% endif %}>Peso Chileno</option>
                    <option value="MXN" {% if plan and plan.auto_recurring.currency_id == 'MXN' %}selected{% endif %}>Peso mexicano</option>
                </select>
            </label>
        </fieldset>

        <button type="submit">{{ 'Atualizar' if plan else 'Cadastrar' }}</button>
    </form>
</body>
</html>

payment/templates/plan/plans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subscriptions</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div>
        <h1 class="page-title">Planos de Assinatura</h1>

        <div class="items-container">
            {% for sub in subscriptions['results'] %}
            <div class="card">
                <h3>{{ sub.reason }}</h3>
                <p><strong>Status:</strong> {{ sub.status }}</p>
                <p><strong>Valor:</strong> R$ {{ sub.auto_recurring.transaction_amount }} / {{ sub.auto_recurring.frequency_type }}</p>
                <p><strong>Repetições:</strong> {{ sub.auto_recurring.repetitions }}</p>
                <p><strong>Criado em:</strong> {{ sub.date_created }}</p>
                <p><strong>Última Modificação:</strong> {{ sub.last_modified }}</p>
                <p><strong>Billing Day:</strong> Dia {{ sub.auto_recurring.billing_day }}</p>
                <p><strong>Teste Grátis:</strong> {{ sub.auto_recurring.free_trial.frequency }} {{ sub.auto_recurring.free_trial.frequency_type }}</p>
                <p><strong>Moeda:</strong> {{ sub.auto_recurring.currency_id }}</p>
                <p><strong>Coletor ID:</strong> {{ sub.collector_id }}</p>
                <p><strong>Subscritos:</strong> {{ sub.subscribed }}</p>
                <p><strong>Application ID:</strong> {{ sub.application_id }}</p>

                <div style="margin-top: 15px;">
                    <a href="{{ url_for('plan.get_plan', plan_id=sub.id) }}"><button>Selecionar</button></a>
                    <a href="{{ url_for('plan.update_plan', plan_id=sub.id) }}"><button>Atualizar</button></a>
                    <a href="{{ sub.init_point }}"><button>Ver Checkout</button></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>