payment/routes/card.py
from flask.blueprints import Blueprint
from flask import render_template, request, jsonify, redirect, url_for
from payment.integrations.payments.card_payment import CardPaymentProxy
from payment.models.card_payment_model import CardPaymentModel
from payment.integrations.client import ClientProxy
from payment.integrations.card import CardProxy
from time import sleep
import mercadopago
import os


card_bp = Blueprint('card', __name__, template_folder='templates')
MP_SDK = mercadopago.SDK(os.environ.get("PAYMENT_MP_PRIVATE_KEY"))
CARD_PAYMENT = CardPaymentProxy()
CARD_PROXY = CardProxy()
CLIENT_PROXY = ClientProxy()


@card_bp.route('/card/', methods=['POST', ])
def payment():
    form_data = {key: request.form.get(key, '').strip() for key in
                 ['amount', 'description', 'identificationType', 'identificationNumber', 'email']}

    if not CARD_PAYMENT.validate_form_data(form_data):
        return jsonify({'error': 'Invalid parameters'}), 400

    try:
        purchase_identification = CARD_PAYMENT.build_purchase_identification(form_data)
        cipher_purchase = CARD_PAYMENT.encrypt_data(purchase_identification)

        return render_template('card/payment_card.html', **form_data,
                               payment_mp_public_key=CARD_PAYMENT.MP_PUBLIC_KEY,
                               purchase_identification=cipher_purchase)
    except Exception as e:
        return jsonify({'error': 'Encryption failed', 'details': str(e)}), 500


@card_bp.route('/card/process_payment/', methods=['POST'])
def process_payment():
    try:
        if not request.is_json:
            print("Invalid request format. Expected JSON")
            return jsonify({"error": "Invalid request format. Expected JSON"}), 400

        data = request.get_json()
        purchase_identification = CARD_PAYMENT.decrypt_purchase_identification(data["purchase_identification"])

        if not CARD_PAYMENT.validate_purchase_data(purchase_identification, data):
            print("Invalid parameters")
            return jsonify({'card/error': 'Invalid parameters'}), 400

        payment_data = CardPaymentModel(
            float(data["transaction_amount"]), data["token"], data["description"], int(data["installments"]),
            data["payment_method_id"], data["payer"]["email"], data["payer"]["identification"]["type"],
            data["payer"]["identification"]["number"],
        )
        payment_response = CARD_PAYMENT.process_payment(payment_data, data["purchase_identification"])

        i = 0
        while payment_response.get('status') == "in_process" or i == 5:
            sleep(1)
            i += 1
            payment_response = CARD_PAYMENT.get_payment(payment_response.get('id'), data["purchase_identification"])

        return jsonify(payment_response), 200
    except ValueError as e:
        print(e)
        return jsonify({"error": str(e)}), 400

    except Exception as e:
        print(f"Error processing payment: {e}")
        return jsonify({"error": "Internal server error"}), 500


@card_bp.route('/card/payment_successful/', methods=['GET', ])
def payment_successful():
    return render_template('card/response.html', response="successful", message="Pagamento aprovado!")


@card_bp.route('/card/payment_error/', methods=['GET', ])
def payment_error():
    return render_template('card/response.html', response="error", message="Pagamento rejeitado! Por favor tente novamente.")


@card_bp.route('/card/register/', methods=['GET', 'POST'])
def register_card():
    if request.method == "POST":
        data = request.get_json()

        response = CLIENT_PROXY.get_clients(data["email"])
        client = response["results"]

        if len(client) == 0:
            return render_template("card/response.html", response="error", message=f"Cliente com e-mail {request.form.get('cardHolderEmail')} não encontrado")

        card_data = {
            "token": data["token"]
        }
        card = CARD_PROXY.add_card(client[0]["id"], card_data)

        if card is None:
            return render_template("card/response.html", response="error", message="Erro durante o cadastramento do cartão.")

        return redirect(url_for("card.get_card", customer_id=client[0]["id"], card_id=card["id"]), 302)
    else:
        return render_template('card/card_register.html', payment_mp_public_key=CARD_PAYMENT.MP_PUBLIC_KEY)


@card_bp.route('/card/<customer_id>/<card_id>/', methods=['POST', ])
def update_card(customer_id, card_id):
    card_data = request.get_json()
    response = CARD_PROXY.update_card(customer_id, card_id, card_data)
    if response is None:
        return render_template('card/response.html', response="error", message="Erro durante atualização do cartão.")
    return render_template('card/response.html', response="successful", message="Cartão atualizado com sucesso!")


@card_bp.route('/card/<customer_id>/<card_id>/delete/', methods=['GET', ])
def delete_card(customer_id, card_id):
    response = CARD_PROXY.delete_card(customer_id, card_id)
    if response is None:
        return render_template('card/response.html', response="error", message="Erro durante a exclusão do cartão.")
    return render_template('card/response.html', response="successful", message="Cartão deletado com sucesso!")


@card_bp.route('/card/<customer_id>/<card_id>/', methods=['GET', ])
def get_card(customer_id, card_id):
    card = CARD_PROXY.get_card(customer_id, card_id)
    if card is None:
        return render_template('card/response.html', response="error", message="Cartão não encontrado.")
    return render_template('card/card.html', card=card)


@card_bp.route('/card/search/', methods=['GET', 'POST'])
def get_cards():
    if request.method == "POST":
        email = request.form.get("cardHolderEmail")
        response = CLIENT_PROXY.get_clients(email)
        client = [client for client in response["results"] if client.get("email") == email]

        if len(client) == 0:
            return render_template('card/response.html', response="error", message=f"Cliente com e-mail {request.form.get('cardHolderEmail')} não encontrado")

        cards = CARD_PROXY.get_cards(client[0]["id"])
        if cards is None:
            return render_template('card/response.html', response="error", message="Nenhum cartão encontrado para este e-mail.")

        print(cards)
        return render_template('card/cards.html', cards=cards)
    else:
        return render_template('card/card_search.html')

payment/templates/card/card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Information</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="card-container">
        <div class="card-logo">
            <img src="{{ card.payment_method.thumbnail }}" alt="{{ card.issuer.name }} Logo">
        </div>
        <div class="card-number">{{ card.first_six_digits }}******{{ card.last_four_digits }}</div>
        <div class="card-details">
            <p><strong>Cardholder:</strong> {{ card.cardholder.name }}</p>
            <p><strong>Issuer:</strong> {{ card.issuer.name }}</p>
            <p><strong>Expires:</strong> {{ card.expiration_month }}/{{ card.expiration_year }}</p>
        </div>
    </div>
</body>
</html>

payment/templates/card/card_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cartão</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <form id="form-checkout" class="form" method="POST">
        <div id="form-checkout__cardNumber" class="container"></div>
        <div id="form-checkout__expirationDate" class="container"></div>
        <div id="form-checkout__securityCode" class="container"></div>
        <input type="text" id="form-checkout__cardholderName" />
        <select id="form-checkout__issuer"></select>
        <select id="form-checkout__installments" hidden="hidden"></select>
        <select id="form-checkout__identificationType"></select>
        <input type="text" id="form-checkout__identificationNumber"/>
        <input type="email" id="form-checkout__cardholderEmail"/>

        <button type="submit" id="form-checkout__submit">Registrar</button>
    </form>

    <script src="https://sdk.mercadopago.com/js/v2"></script>
    <script>
        const mp = new MercadoPago("{{ payment_mp_public_key }}");
        const cardForm = mp.cardForm({
            amount: "0",
            iframe: true,
            form: {
                id: "form-checkout",
                cardNumber: {
                    id: "form-checkout__cardNumber",
                    placeholder: "Número do cartão",
                },
                expirationDate: {
                    id: "form-checkout__expirationDate",
                    placeholder: "MM/YY",
                },
                securityCode: {
                    id: "form-checkout__securityCode",
                    placeholder: "Código de segurança",
                },
                cardholderName: {
                    id: "form-checkout__cardholderName",
                    placeholder: "Titular do cartão",
                },
                issuer: {
                    id: "form-checkout__issuer",
                    placeholder: "Banco emissor",
                },
                installments: {
                    id: "form-checkout__installments",
                    placeholder: "Parcelas",
                },
                identificationType: {
                    id: "form-checkout__identificationType",
                    placeholder: "Tipo de documento",
                },
                identificationNumber: {
                    id: "form-checkout__identificationNumber",
                    placeholder: "Número do documento",
                },
                cardholderEmail: {
                    id: "form-checkout__cardholderEmail",
                    placeholder: "E-mail",
                },
            },
            callbacks: {
                onFormMounted: error => {
                    if (error) return console.warn("Form Mounted handling error: ", error);
                    console.log("Form mounted");
                },
                onSubmit: event => {
                    event.preventDefault();

                    const {
                        paymentMethodId: payment_method_id,
                        issuerId: issuer_id,
                        cardholderEmail: email,
                        amount,
                        token,
                        installments,
                        identificationNumber,
                        identificationType,
                    } = cardForm.getCardFormData();

                    fetch(window.location.href, {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json"
                        },
                        body: JSON.stringify({ token: token, email: email})
                    }).then(response => {
                        if (response.redirected) {
                            window.location.href = response.url; // Redirect if necessary
                        }
                    });
                }
            }
        });

    </script>
</body>
</html>

payment/templates/card/card_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cartão</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <form id="form-checkout" class="form" action="" method="post">
        <label for="cardHolderEmail">E-mail:</label><br>
        <input type="email" id="cardHolderEmail"/>

        <button type="submit" id="form-checkout__submit">Buscar</button>
    </form>
</body>
</html>

payment/templates/card/cards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Information</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {% for card in cards %}
    <div class="card-container">
        <div class="card-logo">
            <img src="{{ card.payment_method.thumbnail }}" alt="{{ card.issuer.name }} Logo">
        </div>
        <div class="card-number">{{ card.first_six_digits }}******{{ card.last_four_digits }}</div>
        <div class="card-details">
            <p><strong>Cardholder:</strong> {{ card.cardholder.name }}</p>
            <p><strong>Issuer:</strong> {{ card.issuer.name }}</p>
            <p><strong>Expires:</strong> {{ card.expiration_month }}/{{ card.expiration_year }}</p>
        </div>
        <a href="{{ url_for('card.get_card', customer_id=card.customer_id, card_id=card.id) }}">Selecionar</a>
        <a href="{{ url_for('card.delete_card', customer_id=card.customer_id, card_id=card.id) }}">Deletar</a>
    </div>
    {% endfor %}
</body>
</html>

payment/templates/card/payment_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cartão</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <form id="form-checkout" class="form">
        <div id="form-checkout__cardNumber" class="container"></div>
        <div id="form-checkout__expirationDate" class="container"></div>
        <div id="form-checkout__securityCode" class="container"></div>
        <input type="text" id="form-checkout__cardholderName" />
        <select id="form-checkout__issuer"></select>
        <select id="form-checkout__installments"></select>
        <select id="form-checkout__identificationType"></select>
        <input type="text" id="form-checkout__identificationNumber" value="{{ identificationNumber }}"/>
        <input type="email" id="form-checkout__cardholderEmail" value="{{ email }}" />

        <button type="submit" id="form-checkout__submit">Pagar</button>
    </form>

    <script src="https://sdk.mercadopago.com/js/v2"></script>
    <script>
        const paymentData = {
            amount: "{{ amount }}",
            description: "{{ description }}",
            purchase_identification: "{{ purchase_identification }}",
        };

        const mp = new MercadoPago("{{ payment_mp_public_key }}");
        const cardForm = mp.cardForm({
            amount: paymentData.amount,
            iframe: true,
            form: {
                id: "form-checkout",
                cardNumber: {
                    id: "form-checkout__cardNumber",
                    placeholder: "Número do cartão",
                },
                expirationDate: {
                    id: "form-checkout__expirationDate",
                    placeholder: "MM/YY",
                },
                securityCode: {
                    id: "form-checkout__securityCode",
                    placeholder: "Código de segurança",
                },
                cardholderName: {
                    id: "form-checkout__cardholderName",
                    placeholder: "Titular do cartão",
                },
                issuer: {
                    id: "form-checkout__issuer",
                    placeholder: "Banco emissor",
                },
                installments: {
                    id: "form-checkout__installments",
                    placeholder: "Parcelas",
                },
                identificationType: {
                    id: "form-checkout__identificationType",
                    placeholder: "Tipo de documento",
                },
                identificationNumber: {
                    id: "form-checkout__identificationNumber",
                    placeholder: "Número do documento",
                },
                cardholderEmail: {
                    id: "form-checkout__cardholderEmail",
                    placeholder: "E-mail",
                },
            },
            callbacks: {
                onFormMounted: error => {
                    if (error) return console.warn("Form Mounted handling error: ", error);
                    console.log("Form mounted");

                    const identificationTypeField = document.getElementById("form-checkout__identificationType");
                    const waitForOptions = setInterval(() => {
                        const options = [...identificationTypeField.options].map(o => o.value);

                        if (options.length > 1) {
                            clearInterval(waitForOptions);
                            identificationTypeField.value = "{{ identificationType }}";
                            identificationTypeField.dispatchEvent(new Event('change'));
                        }
                    }, 500);
                },
                onSubmit: async event => {
                    event.preventDefault();

                    const {
                        paymentMethodId: payment_method_id,
                        issuerId: issuer_id,
                        cardholderEmail: email,
                        amount,
                        token,
                        installments,
                        identificationNumber,
                        identificationType,
                    } = cardForm.getCardFormData();

                    const response = await fetch("{{ url_for('card.process_payment') }}", {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({
                            token,
                            issuer_id,
                            payment_method_id,
                            transaction_amount: Number(amount),
                            installments: Number(installments),
                            description: paymentData.description,
                            payer: {
                                email,
                                identification: {
                                    type: identificationType,
                                    number: identificationNumber,
                                },
                            },
                            purchase_identification: paymentData.purchase_identification,
                        }),
                    });

                    const paymentResult = await response.json();

                    if (paymentResult.status === "approved") {
                        window.location.href = "/card/payment_successful";
                    } else {
                        window.location.href = "/card/payment_error";
                    }
                }
            },
        });
    </script>
</body>
</html>

payment/templates/card/successful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Approved</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="status-container success" id="payment-approved">
        <div class="status-icon">✅</div>
        <div class="status-message">Payment Approved! 🎉</div>
        <button class="btn-back" onclick="window.location.href='/'">Go Back Home</button>
    </div>
</body>
</html>